"""LightSensor v3 RP2040/ADS1220 driver and GUI."""

from lightmeter.port_detect import autodetect_port
from lightmeter.sensor import (
    MAX_DARK_OFFSET_V,
    MAX_WINDOW,
    PROTO_VERSION,
    DeviceError,
    DeviceInfo,
    DeviceState,
    DeviceStatus,
    ErrorEvent,
    LightSensor,
    Profile,
    ProtocolError,
    RawSample,
    SampleStatus,
    StopReason,
    StorageState,
    StreamConfig,
    StreamFormat,
    StreamHeader,
    StreamMode,
    StreamStopped,
    VoltageSample,
)

__all__ = [
    "DeviceError",
    "DeviceInfo",
    "DeviceState",
    "DeviceStatus",
    "ErrorEvent",
    "LightSensor",
    "MAX_DARK_OFFSET_V",
    "MAX_WINDOW",
    "PROTO_VERSION",
    "Profile",
    "ProtocolError",
    "RawSample",
    "SampleStatus",
    "StopReason",
    "StorageState",
    "StreamConfig",
    "StreamFormat",
    "StreamHeader",
    "StreamMode",
    "StreamStopped",
    "VoltageSample",
    "autodetect_port",
]
